# I am a comment, and I want to say that the variable CC will be
# the compiler to use.
CC=g++
# Hey!, I am comment number 2. I want to say that CFLAGS will be the
# options I'll pass to the compiler.
CFLAGS=-c -Wall
DFLAGS=-g

all: EDA

EDA: main.o cell.o
	$(CC) $(DFLAGS) main.o cell.o -o EDA

main.o: main.cpp
	$(CC) $(DFLGAS) $(CFLAGS) main.cpp

cell.o: cell.cpp
	$(CC) $(DFLGAS) $(CFLAGS) cell.cpp

clean:
	rm *o EDA
