######################################################################
# Automatically generated by qmake (3.0) Thu Apr 28 18:44:20 2016
######################################################################

TEMPLATE = app
TARGET = withQt
INCLUDEPATH += .

# Input
HEADERS += cell.h
SOURCES += cell.cpp main.cpp
